services:
  turboist:
    image: tinyops/turboist:1.0.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./data:/app/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          # Required only for aragon hashing
          memory: 128M
