package handlers_test

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"testing"

	"github.com/lebe-dev/turboist/internal/auth"
	"github.com/lebe-dev/turboist/internal/db"
	"github.com/lebe-dev/turboist/internal/httpapi"
	"github.com/lebe-dev/turboist/internal/httpapi/dto"
	"github.com/lebe-dev/turboist/internal/httpapi/handlers"
	"github.com/lebe-dev/turboist/internal/repo"
)

// TestFederationEnable_SetsFlagAndSelfRow asserts that enabling federation flips
// the project's isFederated flag and inserts the owner is_owner=1 self-row in
// federated_projects (US-1.1 AC1).
func TestFederationEnable_SetsFlagAndSelfRow(t *testing.T) {
	e := setupAPIEnv(t)
	ctx := createTestContext(t, e, "Work")
	p := createTestProject(t, e, ctx.ID, "Shared")
	if p.IsFederated {
		t.Fatalf("project should start non-federated")
	}

	resp, body := doReq(t, e.app, e.authedReq(t, http.MethodPost,
		fmt.Sprintf("/api/v1/projects/%d/federation/enable", p.ID), nil))
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("enable: got %d, want 200; body: %s", resp.StatusCode, body)
	}
	var got dto.ProjectDTO
	if err := json.Unmarshal(body, &got); err != nil {
		t.Fatalf("parse: %v", err)
	}
	if !got.IsFederated {
		t.Errorf("returned project isFederated: got false, want true")
	}

	// The owner self-row exists: is_owner=1, peer == origin == this instance.
	self, err := e.fedProjects.SelfRow(context.Background(), p.ID)
	if err != nil {
		t.Fatalf("self-row not found: %v", err)
	}
	if !self.IsOwner {
		t.Errorf("self-row is_owner: got false, want true")
	}
	if self.PeerInstanceURL != testBaseURL || self.OriginInstanceURL != testBaseURL {
		t.Errorf("self-row instance urls: peer=%q origin=%q, want both %q",
			self.PeerInstanceURL, self.OriginInstanceURL, testBaseURL)
	}
	if self.ProtocolVersion < 1 {
		t.Errorf("self-row protocol_version: got %d, want >= 1", self.ProtocolVersion)
	}
}

// TestFederationEnable_Idempotent asserts that enabling federation twice is a
// no-op the second time: still 200, no duplicate self-row, joined_at preserved
// (US-1.1 AC1 idempotency).
func TestFederationEnable_Idempotent(t *testing.T) {
	e := setupAPIEnv(t)
	ctx := createTestContext(t, e, "Work")
	p := createTestProject(t, e, ctx.ID, "Shared")

	enableURL := fmt.Sprintf("/api/v1/projects/%d/federation/enable", p.ID)
	resp, body := doReq(t, e.app, e.authedReq(t, http.MethodPost, enableURL, nil))
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("first enable: got %d, want 200; body: %s", resp.StatusCode, body)
	}
	first, err := e.fedProjects.SelfRow(context.Background(), p.ID)
	if err != nil {
		t.Fatalf("self-row after first enable: %v", err)
	}

	resp2, body2 := doReq(t, e.app, e.authedReq(t, http.MethodPost, enableURL, nil))
	if resp2.StatusCode != http.StatusOK {
		t.Fatalf("second enable: got %d, want 200; body: %s", resp2.StatusCode, body2)
	}

	rows, err := e.fedProjects.ListByProject(context.Background(), p.ID)
	if err != nil {
		t.Fatalf("list rows: %v", err)
	}
	if len(rows) != 1 {
		t.Errorf("federated_projects rows after double enable: got %d, want 1", len(rows))
	}
	second, err := e.fedProjects.SelfRow(context.Background(), p.ID)
	if err != nil {
		t.Fatalf("self-row after second enable: %v", err)
	}
	if !second.JoinedAt.Equal(first.JoinedAt) {
		t.Errorf("joined_at changed on idempotent re-enable: %v -> %v", first.JoinedAt, second.JoinedAt)
	}
}

// TestFederationEnable_KeypairExists asserts that enabling federation guarantees
// this instance has generated its trust-plane keypair (US-1.1 AC4).
func TestFederationEnable_KeypairExists(t *testing.T) {
	e := setupAPIEnv(t)
	ctx := createTestContext(t, e, "Work")
	p := createTestProject(t, e, ctx.ID, "Shared")

	// No keypair before enabling.
	if _, err := e.fedKeys.Get(context.Background()); !errors.Is(err, repo.ErrNotFound) {
		t.Fatalf("expected no keypair before enable, got err=%v", err)
	}

	resp, body := doReq(t, e.app, e.authedReq(t, http.MethodPost,
		fmt.Sprintf("/api/v1/projects/%d/federation/enable", p.ID), nil))
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("enable: got %d, want 200; body: %s", resp.StatusCode, body)
	}

	keys, err := e.fedKeys.Get(context.Background())
	if err != nil {
		t.Fatalf("keypair not generated by enable: %v", err)
	}
	if keys.PublicKey == "" || keys.NodeID == "" {
		t.Errorf("keypair incomplete: pub=%q node=%q", keys.PublicKey, keys.NodeID)
	}
}

// TestFederationEnable_ListReturnsFlag asserts that the projects.list payload
// carries isFederated so the UI can render the badge (US-1.1 AC2).
func TestFederationEnable_ListReturnsFlag(t *testing.T) {
	e := setupAPIEnv(t)
	ctx := createTestContext(t, e, "Work")
	p := createTestProject(t, e, ctx.ID, "Shared")

	resp, body := doReq(t, e.app, e.authedReq(t, http.MethodPost,
		fmt.Sprintf("/api/v1/projects/%d/federation/enable", p.ID), nil))
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("enable: got %d, want 200; body: %s", resp.StatusCode, body)
	}

	listResp, listBody := doReq(t, e.app, e.authedReq(t, http.MethodGet, "/api/v1/projects/", nil))
	if listResp.StatusCode != http.StatusOK {
		t.Fatalf("list: got %d, want 200; body: %s", listResp.StatusCode, listBody)
	}
	var page dto.PagedResponse[dto.ProjectDTO]
	if err := json.Unmarshal(listBody, &page); err != nil {
		t.Fatalf("parse list: %v", err)
	}
	var found bool
	for _, item := range page.Items {
		if item.ID == p.ID {
			found = true
			if !item.IsFederated {
				t.Errorf("listed project isFederated: got false, want true")
			}
		}
	}
	if !found {
		t.Errorf("enabled project %d not present in list", p.ID)
	}
}

// TestFederationEnable_NonExistentProject asserts a 404 for an unknown project.
func TestFederationEnable_NonExistentProject(t *testing.T) {
	e := setupAPIEnv(t)
	resp, body := doReq(t, e.app, e.authedReq(t, http.MethodPost,
		"/api/v1/projects/99999/federation/enable", nil))
	if resp.StatusCode != http.StatusNotFound {
		t.Fatalf("enable unknown project: got %d, want 404; body: %s", resp.StatusCode, body)
	}
}

// TestFederationEnable_KeyMissing asserts that when federation is NOT configured
// (no FEDERATION_KEY → nil service), the enable route returns
// CodeFederationKeyMissing rather than silently flipping the flag (US-1.1 AC4).
func TestFederationEnable_KeyMissing(t *testing.T) {
	dir := t.TempDir()
	d, err := db.Open(filepath.Join(dir, "nofed.db"))
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	t.Cleanup(func() { _ = d.Close() })
	if err := db.RunMigrations(context.Background(), d); err != nil {
		t.Fatalf("migrate: %v", err)
	}

	issuer := auth.NewJWTIssuer([]byte("test-secret-key-32-bytes-padding!"))
	users := repo.NewUserRepo(d)
	if _, err := users.Create(context.Background(), "admin", "h"); err != nil {
		t.Fatalf("seed user: %v", err)
	}
	apiTokens := repo.NewAPITokenRepo(d)
	salt := []byte("test-api-token-salt-32-bytes-pad!")
	deps := httpapi.Deps{JWTIssuer: issuer, UserRepo: users, APITokenRepo: apiTokens, APITokenSalt: salt}
	app := httpapi.NewApp(deps)
	api := httpapi.RegisterRoutes(app, deps)
	// Federation NOT configured: pass a nil service (mirrors FEDERATION_KEY unset).
	handlers.NewFederationAdminHandler(nil).Register(api.Group("", httpapi.RequireJWTAuth()))

	tok, _, err := issuer.Issue(1, 1)
	if err != nil {
		t.Fatalf("issue token: %v", err)
	}
	req := httptest.NewRequest(http.MethodPost, "/api/v1/projects/1/federation/enable", http.NoBody)
	req.Header.Set("Authorization", "Bearer "+tok)
	resp, err := app.Test(req)
	if err != nil {
		t.Fatalf("test: %v", err)
	}
	if resp.StatusCode != http.StatusConflict {
		t.Fatalf("enable without federation key: got %d, want 409", resp.StatusCode)
	}
	var env struct {
		Error struct {
			Code string `json:"code"`
		} `json:"error"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&env); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if env.Error.Code != httpapi.CodeFederationKeyMissing {
		t.Errorf("error code: got %q, want %q", env.Error.Code, httpapi.CodeFederationKeyMissing)
	}
}
